spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to My Cards related prod APIs"
  contactDetails:
    name: "PK - Owner"
    email: "pk@bank.com"
  onCallSupport:
    -(111)111-1234
    -(111)111-1345